version: '3.8'
services:
  react-app:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  node-api:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/foodchatbot
    depends_on:
      - mongodb

  python-api:
    build: ./chatbot-api
    ports:
      - "8000:8000"
    volumes:
      - ./chatbot-api:/app

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: